services:
  jenkins: &jenkins-svc
    extends:
      file: ../fragments/jenkins-volume.yaml
      service: jenkins
    image: jenkins/jenkins:${JENKINS_IMAGE_TAG:-latest}
    container_name: jenkins-${JENKINS_IMAGE_TAG:-latest}
    ports:
      - ${JENKINS_PORT:-8080}:8080
